export const STANDARDS = [
  {
    id: "R-01",
    risk: "High",
    profile: "core",
    requirement: "An explicit Agent loop separates model decisions from external execution.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bAgentRuntime\b/, reason: "Named agent runtime" },
      { pattern: /\b(observe|think|act)\b/, reason: "Observe/think/act loop primitive" },
      { pattern: /tool call/i, reason: "Tool-call step in an agent loop" },
      { pattern: /\bWorkflowGraph\b/, reason: "Workflow graph runtime" },
    ],
    test: [{ pattern: /agent.?loop|maxSteps|runtime\.run/i, reason: "Runtime or loop test" }],
    documentation: [{ pattern: /agent loop|runtime separates/i, reason: "Documented agent loop" }],
    remediation: "Introduce an explicit runtime loop that treats model output as a decision, not as a direct side effect.",
    acceptance: "Model decisions and tool execution are separate types or stages, with tests covering a full loop.",
  },
  {
    id: "R-02",
    risk: "High",
    profile: "core",
    requirement: "Model output or tool intent is schema-validated.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    requiresStructural: true,
    code: [
      { pattern: /\bzod\b|\bZod/i, reason: "Zod schema validation" },
      { pattern: /\bJSON\.parse\b/, reason: "JSON parsing of model output" },
      { pattern: /\baskJson\b|\bstructured(Output|Parse)?\b/i, reason: "Structured output helper" },
      { pattern: /\bschema\b/, reason: "Schema validation" },
    ],
    test: [{ pattern: /invalid json|schema|parse.?fail/i, reason: "Parse-failure test" }],
    documentation: [{ pattern: /schema-validat|JSON Schema|zod/i, reason: "Documented schema validation" }],
    remediation: "Validate model output and tool intent against a schema and handle parse failures without executing tools.",
    acceptance: "Invalid model output is rejected or recovered; no tool runs on unparsed intent.",
  },
  {
    id: "R-03",
    risk: "High",
    profile: "core",
    requirement: "Each run has a maximum step count, duration, or call budget.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    requiresStructural: true,
    code: [
      { pattern: /\bmaxSteps\b/, reason: "Maximum step count" },
      { pattern: /\bmaxDuration\b|\btimeout\b/i, reason: "Duration or timeout budget" },
      { pattern: /\bLoopGuard\b|\bbudget\b/i, reason: "Loop guard or budget" },
    ],
    test: [{ pattern: /maxSteps|timeout|budget|loop guard/i, reason: "Stop-condition test" }],
    documentation: [{ pattern: /maxSteps|timeout|budget|step limit/i, reason: "Documented run budget" }],
    remediation: "Add a hard stop: max steps, wall-clock timeout, or tool-call budget, and test that it fires.",
    acceptance: "A run cannot continue indefinitely; the stop path is covered by a test.",
  },
  {
    id: "R-04",
    risk: "Medium",
    profile: "core",
    requirement: "Task state is persistent or the design explicitly declares statelessness.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\bSessionStore\b|\bTaskState\b/, reason: "Session or task state type" },
      { pattern: /\bsession\b/i, reason: "Session handling" },
    ],
    test: [{ pattern: /session|task state|stateless/i, reason: "Session or statelessness test" }],
    documentation: [{ pattern: /stateless|session|task state/i, reason: "Documented state design" }],
    remediation: "Persist task state across steps, or document an explicit stateless design and its limits.",
    acceptance: "State is stored and restored, or the report records a deliberate stateless design.",
  },
  {
    id: "R-05",
    risk: "Medium",
    profile: "core",
    requirement: "Context has a length/token budget and truncation strategy.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\bContextBuilder\b|\bcompact\b|\blimitContext\b|\bmaxContext\b/, reason: "Context budget or compaction" },
      { pattern: /\btruncat/i, reason: "Truncation strategy" },
    ],
    test: [{ pattern: /truncat|context (limit|budget)|compact/i, reason: "Context-limit test" }],
    documentation: [{ pattern: /context (limit|budget)|truncat|token/i, reason: "Documented context budget" }],
    remediation: "Cap context size and define what is dropped when the cap is hit.",
    acceptance: "Oversized context is compacted or truncated; the strategy is tested or traced.",
  },
  {
    id: "T-01",
    risk: "High",
    profile: "core",
    requirement: "Tool input, output, and error boundaries are explicit.",
    checkStrategy: "automated",
    applicability: "hasTools",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bToolRegistry\b/, reason: "Tool registry" },
      { pattern: /\binputSchema\b/, reason: "Tool input schema" },
      { pattern: /tool.*schema/i, reason: "Tool schema" },
    ],
    test: [{ pattern: /tool.*(schema|error)|invalid (argument|input)/i, reason: "Tool contract test" }],
    documentation: [{ pattern: /tool (schema|input|output|error)/i, reason: "Documented tool contracts" }],
    remediation: "Give every tool an input schema, a result type, and a mapped error path.",
    acceptance: "Invalid tool input fails closed; tool errors are transformed rather than thrown raw to the model.",
  },
  {
    id: "T-02",
    risk: "Critical",
    profile: "core",
    requirement: "Tool calls have permission and scope checks.",
    checkStrategy: "automated",
    applicability: "hasTools",
    missingMeans: "fail",
    criticalPass: "structural+verified",
    code: [
      { pattern: /\bPermissionGate\b/, reason: "Permission gate" },
      { pattern: /\bauthorize\s*\(/, reason: "Authorization call" },
      { pattern: /\ballowlist\b|\bwhitelist\b/i, reason: "Tool allowlist" },
      { pattern: /\bcheckPermission\b|\bhasPermission\b/, reason: "Permission helper" },
    ],
    test: [
      { pattern: /unauthorized|not authorized|permission denied|out of scope/i, reason: "Unauthorized or out-of-scope call is rejected" },
    ],
    configuration: [{ pattern: /\ballowlist\b|\bpermissions\b|\bscopes\b/i, reason: "Permission configuration" }],
    documentation: [{ pattern: /PermissionGate|permission and scope|permission check/i, reason: "Documented permission checks" }],
    remediation: "Route every tool call through a permission and scope gate. Reject unauthorized and out-of-scope calls, and record the decision.",
    acceptance: "Unauthorized and out-of-scope calls are rejected; traces record allow/deny; no bypass path exists around the gate.",
  },
  {
    id: "T-03",
    risk: "Critical",
    profile: "core",
    requirement: "Dangerous actions such as deletion, payment, publishing, or sending messages require confirmation.",
    checkStrategy: "automated",
    applicability: "hasDangerousActions",
    missingMeans: "fail",
    criticalPass: "structural+verified",
    code: [
      { pattern: /\bconfirm(ation)?\b/i, reason: "Confirmation step" },
      { pattern: /\bapproval\b|\bhuman.?approval\b/i, reason: "Approval gate" },
      { pattern: /\bApprovalGate\b/, reason: "Named approval gate" },
    ],
    test: [{ pattern: /approval|confirm|refuse|rejected.*dangerous/i, reason: "Dangerous-action confirmation test" }],
    documentation: [{ pattern: /human (approval|confirm)|dangerous action/i, reason: "Documented approval requirement" }],
    remediation: "Require an approval record before delete, pay, publish, or message actions, and keep a refusal path.",
    acceptance: "Dangerous tools cannot run without a recorded confirmation; refusal is tested.",
  },
  {
    id: "O-01",
    risk: "Medium",
    profile: "core",
    requirement: "Every run has a trace correlated to run/session/task.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\bTraceLogger\b|\btrace\.record\b/, reason: "Trace writer" },
      { pattern: /\bjsonl\b/i, reason: "JSONL trace output" },
      { pattern: /\btraceId\b|\brunId\b|\bsessionId\b/, reason: "Correlation identifiers" },
    ],
    test: [{ pattern: /trace|correlation|runId/i, reason: "Trace correlation test" }],
    documentation: [{ pattern: /trace|OpenTelemetry|jsonl/i, reason: "Documented tracing" }],
    remediation: "Write a per-run trace with run, session, or task identifiers.",
    acceptance: "A completed run produces a correlated trace file or span.",
  },
  {
    id: "O-02",
    risk: "Medium",
    profile: "core",
    requirement: "Call count, latency, token/cost, or explicit cost-unavailable state is recorded.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\blatency\b/i, reason: "Latency recording" },
      { pattern: /\bestimatedCost\b|\busage\b|\btoolCalls\b/, reason: "Cost or usage recording" },
    ],
    test: [{ pattern: /latency|estimatedCost|token|toolCalls/i, reason: "Metrics test" }],
    documentation: [{ pattern: /latency|cost|token usage/i, reason: "Documented metrics" }],
    remediation: "Record latency and token/cost, or an explicit cost-unavailable marker.",
    acceptance: "A run report includes call count and latency or cost (or cost-unavailable).",
  },
  {
    id: "O-03",
    risk: "High",
    profile: "core",
    requirement: "Logs, traces, and errors do not expose keys, passwords, or complete sensitive data.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    requiresStructural: true,
    code: [
      { pattern: /\bredact\b|\bsanitize\b/i, reason: "Redaction or sanitization" },
      { pattern: /\bsecret\b|\bapi.?key\b/i, reason: "Secret handling" },
    ],
    test: [{ pattern: /redact|does not (log|expose)|secret|api.?key/i, reason: "Log-disclosure test" }],
    documentation: [{ pattern: /redact|sensitive data|do not log secrets/i, reason: "Documented redaction" }],
    remediation: "Redact secrets and raw sensitive payloads from logs, traces, and errors, and add a disclosure test.",
    acceptance: "A test shows API keys and passwords are not present in log or trace output.",
  },
  {
    id: "E-01",
    risk: "High",
    profile: "core",
    requirement: "Fixed evaluations or regression tests exist; manual demos alone are insufficient.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    testSufficient: true,
    code: [
      { pattern: /\beval\b|\bsmoke.?test\b|\bregression\b/i, reason: "Evaluation or regression harness" },
      { pattern: /\btest\s*\(/, reason: "Test function" },
    ],
    test: [
      { pattern: /\btest\s*\(|assert|expected unauthorized|describe\s*\(/, reason: "Repeatable test" },
    ],
    documentation: [{ pattern: /npm test|pytest|eval suite|smoke test/i, reason: "Documented test command" }],
    remediation: "Add a repeatable test or eval command with expected results; do not rely on manual demos.",
    acceptance: "A documented command produces a pass/fail result without a human demo.",
  },
  {
    id: "E-02",
    risk: "Medium",
    profile: "core",
    requirement: "Failures can be attributed to Prompt, Tool, Retrieval, Model, State, Safety, or similar category.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\bfailureCategory\b|\bclassifyFailure\b/, reason: "Failure classification" },
      { pattern: /prompt.*tool.*state/i, reason: "Failure taxonomy" },
    ],
    test: [{ pattern: /failureCategory|classifyFailure/i, reason: "Failure-classification test" }],
    documentation: [{ pattern: /failure (categor|classif)/i, reason: "Documented failure taxonomy" }],
    remediation: "Tag failures with a small taxonomy (Prompt, Tool, Retrieval, Model, State, Safety).",
    acceptance: "Failed runs include a category that can be compared across traces.",
  },
  {
    id: "S-01",
    risk: "High",
    profile: "core",
    requirement: "Prompt injection, data exfiltration, and tool abuse are tested or input sources are explicitly constrained.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /prompt.?injection|exfiltration|tool.?abuse/i, reason: "Security control or test for agent abuse" },
      { pattern: /\brisk\b/, reason: "Risk policy" },
    ],
    testSufficient: true,
    test: [{ pattern: /prompt.?injection|exfiltration|tool.?abuse/i, reason: "Security fixture" }],
    documentation: [{ pattern: /prompt injection|exfiltration|tool abuse|untrusted input/i, reason: "Documented untrusted-input policy" }],
    remediation: "Add fixtures for injection, exfiltration, and unauthorized tools, or constrain untrusted inputs explicitly.",
    acceptance: "At least one automated case rejects injection or unauthorized tool use.",
  },
  {
    id: "K-01",
    risk: "Medium",
    profile: "rag",
    requirement: "Chunks have stable IDs, sources, and locations.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\bchunk\b/i, reason: "Chunk handling" },
      { pattern: /\bchunkId\b|\bsource\b|\blocation\b/, reason: "Chunk identity fields" },
    ],
    test: [{ pattern: /chunkId|chunk.*source/i, reason: "Chunk identity test" }],
    documentation: [{ pattern: /chunk (id|source|schema)/i, reason: "Documented chunk schema" }],
    remediation: "Give chunks stable IDs plus source and location metadata.",
    acceptance: "Indexed chunks can be traced back to a document location.",
  },
  {
    id: "K-02",
    risk: "High",
    profile: "rag",
    requirement: "Query and documents use compatible embeddings with failure handling.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bembedding\b/i, reason: "Embedding adapter" },
      { pattern: /\bembed\(/i, reason: "Embed call" },
    ],
    test: [{ pattern: /embedding|embed.*fail/i, reason: "Embedding failure test" }],
    documentation: [{ pattern: /embedding model|compatible embedding/i, reason: "Documented embedding configuration" }],
    remediation: "Use one embedding family for queries and documents, and handle embedder failures.",
    acceptance: "Embed failures are handled; query and document vectors are compatible.",
  },
  {
    id: "K-03",
    risk: "Medium",
    profile: "rag",
    requirement: "Retrieval records top-K, similarity, or recall evidence.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\bretriev/i, reason: "Retriever" },
      { pattern: /\btopK\b|\btop_k\b|\bsimilarity\b/i, reason: "Retrieval scores" },
    ],
    test: [{ pattern: /topK|similarity|recall/i, reason: "Retrieval evidence test" }],
    documentation: [{ pattern: /top-K|similarity|retriev/i, reason: "Documented retrieval evidence" }],
    remediation: "Record top-K and similarity (or equivalent) on each retrieval.",
    acceptance: "A trace shows what was retrieved and why.",
  },
  {
    id: "K-04",
    risk: "High",
    profile: "rag",
    requirement: "Context construction deduplicates, truncates, and prevents unsupported answers.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bContextBuilder\b|\bdedup/i, reason: "Context construction" },
      { pattern: /unsupported|ground(ed|ing)/i, reason: "Grounding or refusal" },
    ],
    test: [{ pattern: /dedup|unsupported|ground/i, reason: "Grounding test" }],
    documentation: [{ pattern: /deduplicat|unsupported answer|ground/i, reason: "Documented grounding policy" }],
    remediation: "Deduplicate and truncate retrieved context, and refuse when evidence is missing.",
    acceptance: "A test covers unsupported questions and duplicate chunks.",
  },
  {
    id: "K-05",
    risk: "Medium",
    profile: "rag",
    requirement: "Indexes support version identification, rebuild, or cache invalidation.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /index.*(version|rebuild)|cache.?invalid/i, reason: "Index versioning or rebuild" },
      { pattern: /\brebuildIndex\b|\bindexVersion\b/, reason: "Index rebuild API" },
    ],
    test: [{ pattern: /rebuild|index version|invalidat/i, reason: "Index rebuild test" }],
    documentation: [{ pattern: /rebuild|index version|cache invalid/i, reason: "Documented index lifecycle" }],
    remediation: "Version the index and provide a rebuild or invalidation path.",
    acceptance: "Operators can tell which index is live and rebuild it.",
  },
  {
    id: "W-01",
    risk: "High",
    profile: "workflow",
    requirement: "Each role has one responsibility and an input/output schema.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bPlanner\b|\bWriter\b|\bReviewer\b|\bCritic\b|\bSupervisor\b/, reason: "Role type" },
    ],
    test: [{ pattern: /planner|reviewer|role.*schema/i, reason: "Role contract test" }],
    documentation: [{ pattern: /planner|reviewer|role/i, reason: "Documented roles" }],
    remediation: "Give each role a single responsibility and typed inputs/outputs.",
    acceptance: "Roles cannot silently take on another role's writes.",
  },
  {
    id: "W-02",
    risk: "High",
    profile: "workflow",
    requirement: "The task goal is explicitly propagated and task drift is checked.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bgoal\b/, reason: "Goal propagation" },
      { pattern: /task drift|topic validation|goal.?check/i, reason: "Drift check" },
    ],
    test: [{ pattern: /goal|drift|off.?topic/i, reason: "Goal-drift test" }],
    documentation: [{ pattern: /task drift|goal propagation/i, reason: "Documented goal checks" }],
    remediation: "Pass the original goal into each stage and reject off-goal output.",
    acceptance: "A drifted draft is detected and sent back with the original goal.",
  },
  {
    id: "W-03",
    risk: "High",
    profile: "workflow",
    requirement: "Observable stop conditions, maximum rework count, and loop detection exist.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /revision (limit|count)|maxRework|loop (guard|detect)/i, reason: "Rework or loop limit" },
      { pattern: /\brouter\b|\bmaxRevisions\b/, reason: "Graph router or revision cap" },
    ],
    test: [{ pattern: /rework|revision limit|loop detect/i, reason: "Loop-limit test" }],
    documentation: [{ pattern: /stop condition|rework|loop detect/i, reason: "Documented stop conditions" }],
    remediation: "Cap rework and detect cycles in the graph router.",
    acceptance: "A looping workflow stops at a configured revision limit.",
  },
  {
    id: "W-04",
    risk: "Medium",
    profile: "workflow",
    requirement: "Reviewer/Critic does not directly modify output; rework uses explicit feedback to the executor.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /ReviewResult|revision path|feedback/i, reason: "Review result type" },
    ],
    test: [{ pattern: /reviewer.*(not|never) (edit|modif)|feedback to/i, reason: "Reviewer isolation test" }],
    documentation: [{ pattern: /reviewer does not|critic.*feedback/i, reason: "Documented reviewer isolation" }],
    remediation: "Keep Reviewer/Critic read-only over the artifact; send feedback to the executor.",
    acceptance: "Review output is feedback, not a silent rewrite of the artifact.",
  },
  {
    id: "SK-01",
    risk: "Medium",
    profile: "skill",
    requirement: "A Skill has a name, purpose, triggers, steps, and acceptance criteria.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /SkillRegistry|SkillManifest/, reason: "Skill registry or manifest" },
    ],
    test: [{ pattern: /SKILL\.md|skill manifest/i, reason: "Skill manifest test" }],
    documentation: [{ pattern: /SKILL\.md|triggers|acceptance criteria/i, reason: "Skill definition document" }],
    remediation: "Add a SKILL.md with name, purpose, triggers, steps, and acceptance criteria.",
    acceptance: "The skill file can be loaded and lists those five fields.",
  },
  {
    id: "SK-02",
    risk: "High",
    profile: "skill",
    requirement: "Skill scripts, templates, and reference resources load on demand.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /SkillRegistry|loadSkill|resource path/i, reason: "On-demand skill loader" },
    ],
    test: [{ pattern: /loadSkill|on demand|resource path/i, reason: "Skill loader test" }],
    documentation: [{ pattern: /on demand|resource path|scripts\/|templates\//i, reason: "Documented skill resources" }],
    remediation: "Load scripts, templates, and references through a registry rather than baking them into every prompt.",
    acceptance: "Resources resolve from declared paths only when the skill is selected.",
  },
  {
    id: "SK-03",
    risk: "Critical",
    profile: "skill",
    requirement: "A Skill cannot bypass tool permissions, workspace limits, or secret protections.",
    checkStrategy: "automated",
    applicability: "always",
    missingMeans: "fail",
    criticalPass: "structural+verified",
    code: [
      { pattern: /PermissionGate|Runtime|workspace/i, reason: "Skill execution through runtime or permission gate" },
    ],
    test: [{ pattern: /skill.*bypass|permission.*skill/i, reason: "Skill permission test" }],
    documentation: [{ pattern: /cannot bypass|PermissionGate|workspace limit/i, reason: "Documented skill isolation" }],
    remediation: "Execute skills only through the same runtime and permission gate as ordinary tool calls.",
    acceptance: "A skill cannot call a disallowed tool or read secrets outside the workspace.",
  },
  {
    id: "SK-04",
    risk: "Medium",
    profile: "skill",
    requirement: "A Skill has a smoke test or task-success evidence.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [{ pattern: /smoke.?test|skill.*test/i, reason: "Skill smoke test" }],
    test: [{ pattern: /smoke|skill/i, reason: "Skill test" }],
    documentation: [{ pattern: /smoke test|task-success/i, reason: "Documented skill test" }],
    remediation: "Add a smoke test or recorded task-success command for the skill.",
    acceptance: "A command demonstrates the skill completes its happy path.",
  },
  {
    id: "B-01",
    risk: "High",
    profile: "browser",
    requirement: "Observe before each action, then observe and verify afterward.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: false,
    code: [
      { pattern: /\bBrowserSession\b|\bPlaywright\b|\bscreenshot\b|\bnavigate\b/, reason: "Browser observation or action" },
    ],
    test: [{ pattern: /observe|screenshot|before.*action/i, reason: "Observe-then-act test" }],
    documentation: [{ pattern: /observe before|screenshot|state machine/i, reason: "Documented observe-act-verify loop" }],
    remediation: "Observe the page before acting, then observe and verify the result.",
    acceptance: "Each action has before/after evidence in the trace.",
  },
  {
    id: "B-02",
    risk: "Critical",
    profile: "browser",
    requirement: "Domain, login, payment, download, and form submission have safety constraints.",
    checkStrategy: "automated",
    applicability: "always",
    missingMeans: "fail",
    criticalPass: "structural+verified",
    code: [
      { pattern: /browser policy|allowedDomains|human confirmation/i, reason: "Browser safety policy" },
    ],
    test: [{ pattern: /domain|login|payment|download|form/i, reason: "Browser constraint test" }],
    documentation: [{ pattern: /allowed domain|login|payment|download/i, reason: "Documented browser constraints" }],
    remediation: "Constrain domains and require confirmation for login, payment, download, and form submission.",
    acceptance: "Disallowed domains and sensitive actions are blocked or confirmed.",
  },
  {
    id: "B-03",
    risk: "Medium",
    profile: "browser",
    requirement: "Loading failures, locator failures, page changes, and dialogs are handled.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /\btimeout\b|\bretry\b|locator|dialog/i, reason: "Browser error handling" },
    ],
    test: [{ pattern: /timeout|locator|dialog|page change/i, reason: "Browser failure test" }],
    documentation: [{ pattern: /timeout|retry|dialog/i, reason: "Documented browser error handling" }],
    remediation: "Handle timeouts, missing locators, navigation, and dialogs with explicit error states.",
    acceptance: "A test covers at least one locator or load failure path.",
  },
  {
    id: "B-04",
    risk: "Medium",
    profile: "browser",
    requirement: "DOM, screenshots, action logs, and final verification evidence are retained.",
    checkStrategy: "automated",
    applicability: "always",
    passWithCodeAndTest: true,
    code: [
      { pattern: /screenshot|artifact|action log/i, reason: "Browser artifacts" },
    ],
    test: [{ pattern: /screenshot|artifact|trace/i, reason: "Artifact retention test" }],
    documentation: [{ pattern: /artifact|screenshot path|trace/i, reason: "Documented artifact paths" }],
    remediation: "Keep screenshots, DOM snapshots, action logs, and a final verification record.",
    acceptance: "A completed browser run stores artifacts under a known path.",
  },
];

export const STANDARDS_BY_ID = Object.fromEntries(STANDARDS.map((item) => [item.id, item]));
